name: target_discovery
version: '1.0.0'
config-version: 2

profile: target_discovery

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  target_discovery:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  target_discovery:
    gene_symbols:
      +column_types:
        ensembl_id: varchar
        gene_symbol: varchar
    disease_names:
      +column_types:
        disease_id: varchar
        disease_name: varchar
